openvpn_servers:
  - key: general
    value:
      port: 22420
      server: "10.8.0.0 255.255.255.0"
      push:
        - '"redirect-gateway def1"'
        - '"route 192.168.22.0 255.255.255.0"'
      no_key_variable:
        - "persist-key"
        - "persist-tun"
      cert: /etc/openvpn/phx_server.crt
      key: /etc/openvpn/phx_server.key
  - key: phx_to_prox
    value:
      port: 22422
      ifconfig: "10.200.0.6 10.200.0.5"
      cert: /etc/openvpn/phx_server.crt
      key: /etc/openvpn/phx_server.key

openvpn_clients:
  - key: phx_to_lt
    value:
      remote: 93.127.213.223
      port: 22423
      ifconfig: "10.200.0.10 10.200.0.9"
      cert: /etc/openvpn/phx_client.crt
      key: /etc/openvpn/phx_client.key

openvpn_certs:
  - ca.crt
  - dh.pem
  - ta.key
  - phx_server.crt
  - phx_client.crt
  - phx_server.key
  - phx_client.key
