---
- name: Get the join command from the master node
  ansible.builtin.shell: "set -o pipefail && kubeadm token create --print-join-command"
  args:
    executable: /usr/bin/bash
  register: join_command
  run_once: true
  delegate_to: "k8-1-proxmox"

- name: Get command output
  ansible.builtin.set_fact:
    join_command: "{{ join_command.stdout }}"

- name: Join worker nodes to the cluster
  ansible.builtin.shell: "{{ join_command }}"
  args:
    executable: /usr/bin/bash
  when: role == "worker"
