---
# handlers file for ssh
- name: Relaod systemd services
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart sshd service
  ansible.builtin.service:
    name: sshd
    state: restarted
