---
- name: Deploy
  hosts: all
  become: true
  gather_facts: true
  roles:
    - {role: ssh, tags: ssh}
    - {role: iptables, tags: iptables}
    - {role: ovpn, tags: ovpn}
    - {role: frr, tags: frr}
