name: ansible-lint

on:
  pull_request:
    branches: ["master"]
jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install ansible-lint with pip
        run: |
          sudo apt update
          sudo apt install pip git
          pip install ansible-core ansible-lint

      - name: Install Ansible Collections
        run: |
          ansible-galaxy collection install -r collections/requirements.yml

      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
