---
name: yaml-lint

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  yaml-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run YAML Lint
        uses: ibiqlik/action-yamllint@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          config_file: .yamllint.yml
